apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: openshift-etcd
  labels:
    k8s-app: etcd
spec:
  ports:
    - $patch: replace
    - name: etcd
      port: 2378
      protocol: TCP

