apiVersion: v1
baseDomain: edge.network
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
kind: InstallConfig
metadata:
  name: cluster
networking:
  machineCIDR: 10.1.1.0/24
  networkType: OpenShiftSDN
platform:
  gcp:
    projectID: openshift-gce-devel
    region: europe-west4
